services:
  # Backend API service
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.backend
    container_name: devops-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: unless-stopped
    networks:
      - devops-network

  # Frontend web service
  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.frontend
    container_name: devops-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - devops-network

# Define network for containers to communicate
networks:
  devops-network:
    driver: bridge